name: file_utils
version: 0.0.3
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: File utils is a collection of the helper methods for file system (basename, chdir, dirempty, dirname, getcwd, glob, mkdir, rm, rmdir, symlink, testfile, touch).
homepage: https://github.com/mezoni/file_utils
dependencies:
  globbing: any
  path: any
dev_dependencies:
  unittest: any
